### ISSUE TITLE
Change color of loadings (arrows and features)

### ISSUE THREAD

**Issue by jmclawson** [jmclawson/stylo2gg#2]
Hi again! I continue to enjoy your package! I am writing up my PhD dissertation where I use it but have one problem with the presentation (which is not really an issue with the package per se but maybe you can help me since you have written the function): how do I change color on the arrows and the words in the PCA (going to move from light gray to something more articulated and have tried all ggplot commands I know but nothing seems to work)? Thanks!

_Originally posted by @doeparen in https://github.com/jmclawson/stylo2gg/issues/1#issuecomment-1221349229_

**Comment by jmclawson** [comment]
@doeparen I pulled this out into a new issue since it wasn’t related to the other one. 

This gray color is currently baked into the function. It shouldn’t be too hard to add another argument to change this color, but I’ve actually been considering refactoring the package altogether to turn the workings into ggplot layers one might build successively instead of having a singular massive `stylo2gg()` function packed to the gills with options. 

Give me a day or two, and I might be able to cobble together a simple solution for the meantime.

**Comment by doeparen** [comment]
Thank you for answering so quickly and taking the time to look at a quick fix. Most appreciated!

**Comment by jmclawson** [comment]
Hello, this should be working now in version 0.8, as of today. The parameters are called "loadings_line_color" and "loadings_word_color" because I wasn't feeling very creative. You can see a few other changes here: https://github.com/jmclawson/stylo2gg/commit/9a06171a09b0c864bd7f545f3fb787ca3ba6df49

**Comment by doeparen** [comment]
Hi, big thanks for the updates! Look forward to trying them out.
