### ISSUE TITLE
Loadings stuck on PC1 and PC2 when trying to plot PC3

### ISSUE THREAD

**Issue by doeparen** [jmclawson/stylo2gg#4]
Hi again!

Sorry for bothering you with another issue, which this time might be a question stemming from my ignorance and is perhaps not an issue with your package as such.

First, some small context that might be useful: I have made an analysis with bootstrapped consensus trees from `stylo()` through which I found five separate styles (via modularity scores in Gephi). Thus, I renamed the documents according to these styles to find out something about their MFW and I plotted the top loadings in a PCA via `stylo2gg()` to make an interpretation of what the most frequently used words are for each style. Four of the styles got a distinct corner in the PCA while the last was spread out over PC1 and PC2. Thus, I now want to compare how the loadings are distributed over the documents/styles on PC3. 

So, to the issue: my goal is to compare the distribution of the top loading on PC3 and maybe PC4 with those on PC1 and PC2 but I have not managed to do it with `stylo2gg()`. My strategy to go around the problem has been to change to `aes(x = PC1, y = PC3)` after the plot is made, but when I do so only the shapes (the documents) alter position while the loadings (the words) stay on the same position (i.e., the loadings keep the original position from the PCA of PC1 and PC2 when I change to the PCA of PC1 and PC3). (This is really annoying since I can see that the fifth style has a distinct position on the third principal component.)

```
style_corpus <- stylo(gui=FALSE,
        analysis.type= "BCT",
        corpus.dir = "/Stylo/corpus",
        pca.visual.flavour = "classic",
        analyzed.features="w",
        ngram.size=1,
        display.on.screen=TRUE,
        sampling="no.sampling",
        mfw.min=50,
        mfw.max=1550)

p <- style_corpus %>% 
  stylo2gg(shapes = TRUE, 
           viz = "pca", 
           top.loadings = 10
           loadings_word_color = "gray18",
           loadings_line_color = "gray88")

p + aes(x = PC1, y = PC3)
```

Best,
Josef

**Comment by jmclawson** [comment]
No need to apologize! I appreciate having someone else using the package to help stretch it to its limits and help establish what the limits should be!

What you're wanting to do is very reasonable. At the moment, things are hard-wired to limit the loadings data to just the first two components [here](https://github.com/jmclawson/stylo2gg/blob/main/R/stylo2gg.R#L939). I would like to open this up with an argument, but I won't have a chance to tinker with it until a couple weeks from now. 

In the meantime, can you double check whether those other components are exported in `s2g_export$loadings`, which should be in your global environment? I *think* they should be, and this data should be sufficient to add an overlay as another layer (or a few, really, if you're adding the loading labels and the arrows/lines). Some considerations: they may look weird unless you scale them to fit within the max/min of the values on the base chart; additionally, be sure both `invert.x` and `invert.y` are set to false in the base chart.

**Comment by doeparen** [comment]
Thank you for answering my question and offering a solution in the future! I can understand that it will take a good deal of thinking and coding to handle.

The `s2g_export` is a `list [3]` with `s2g_export$z`, `s2g_export$pca`, and `s2g_export$pca_details`. The loadings can be found in`s2g_export$z`, which here is a `Type` called `list [380 x 1550] (S3: data.frame)`, where each word (in this case 1550) is constituted by as many vectors (positive and negative) as there are documents in the corpus (in this case 380). Further, we have `s2g_export$pca`, a `list [5] (S3: procomp)`. In `s2g_export$pca$rotation`, a `Type` called `double [1550 x 380]`, where each word is coupled with as many PC (each with a vector value) as there are documents (i.e., 380). (In `s2g_export$pca$x`, each document gets its position along the 380 PC as well.) The `s2g_export$pca_details`, a  `list [6] (S3: summary.procomp)`, seems to hold the same information as `s2g_export$pca` with the exception of `s2g_export$pca_details$importance`, stating the Standard deviation and Proportion of Variance for each PC.

Not sure how to plot the loadings on the other PCs at the moment, but will do some experiments this week!

**Comment by jmclawson** [comment]
I think I have this working now. Would you mind upgrading to version 0.9 and testing it out? Keep in mind the following:

- The new parameters are `pc.x` and `pc.y`. Naturally, they default to `1` and `2`, but you can select different components by changing these numbers.
- Loadings will also reflect the chosen components. This means the `top.loadings` will vary when viewing different components.
- For sake of consistency, this version renames four parameters to replace underscores with dots: `loadings.spacer`, `loadings.line.color`, `loadings.word.color`, and `loadings.upper`

Independent of these new options, please also let me know if you see any surprising changes to output. (At the same time I did this, I did some other kinds of rewiring to the code to make it easier to work with. It shouldn't have changed anything, but there's always the possibility that I've accidentally left some wires disconnected.)

**Comment by jmclawson** [comment]
Here's some sample code and output:

```{r}
federalist <- 
  stylo(gui=FALSE,
        corpus.dir = "~/GitHub/stylo2gg/federalist",
        analysis.type="PCR",
        pca.visual.flavour = "symbols",
        analyzed.features="w",
        ngram.size=1,
        display.on.screen=FALSE,
        sampling="no.sampling",
        culling.max=75,
        culling.min=75,
        mfw.min=900,
        mfw.max=900)

federalist |> 
  stylo2gg(viz="pca",
           shapes = FALSE, 
           labeling = 2,
           top.loadings = 3)
```

![pc1-and-pc2](https://user-images.githubusercontent.com/3894072/222869711-088effa5-c261-4baf-8a22-9b74a836ff2e.png)

```{r}
federalist |> 
  stylo2gg(viz="pca",
           shapes = FALSE, 
           labeling = 2,
           pc.x = 3,
           pc.y = 4,
           top.loadings = 3)
```

![pc3-and-pc4](https://user-images.githubusercontent.com/3894072/222869741-dd2343d6-adaf-43b2-9e5a-fde9d7270583.png)

**Comment by doeparen** [comment]
Works like a charm – thanks for the update, James! Thus far I have found no differences whatsoever, so this issue can be closed. Take care!

**Comment by jmclawson** [comment]
Glad it works! And this is something I wanted too, so thanks for requesting it!
